### ISSUE TITLE
Move to anaconda.org

### ISSUE THREAD

**Issue by mattip** [MacPython/cython-wheels#3]
@ogrisel requested that projects move off the rackspace hosting and onto https://anaconda.org/multibuild-wheels-staging/ and https://anaconda.org/scipy-wheels-nightly/ instead, as the free hosting from rackspace is ending. 

Steps to be taken:
- [ ] add someone from the cython org to the list of owners of the organizations above
- [ ] modify the CI to point to the new orgs.
- [ ] create appropriate tokens to enable upload at `https://anaconda.org/<org>/settings/access`
- [ ] add those tokens to CI

@ogrisel, @tylerjereddy or @mattip could execute the first step once the designated user has registered with anaconda.org.

If you wish to remain on travis/appveyor, you can use MacPython/scipy-wheels#69 as a basis, even though it is not merged yet. Numpy moved to Azure in MacPython/numpy-wheels#78, but only builds for x86 architectures.

**Comment by scoder** [comment]
Thanks for the heads-up. Is this only about the artefact upload/hosting or also about the build integration with travis/appveyor?

**Comment by mattip** [comment]
Only about artefact uploading hosting. The move to Azure was an added benefit since the Appveyor builds of windows wheels were soooo slow for NumPy

**Comment by scoder** [comment]
> Appveyor builds of windows wheels were soooo slow for NumPy

Not just for you…

**Comment by mattip** [comment]
The first stage is the tricky one: someone from the cython org needs to registers with anaconda.org and get permissions to create secrets (or you recruit one of the current anaconda.org group maintainers to create the secrets for you) so you can add them to your CI here, whichever CI you choose to use.

**Comment by scoder** [comment]
I'll push to Github releases then for now.  Let's see where that gets us. Certainly easier than writing a new build script for anything.
