### ISSUE TITLE
Aarch64 wheels not available on pypi.org

### ISSUE THREAD

**Issue by tbbharaj** [MacPython/cython-wheels#6]
Builds for aarch64 wheels are completing successfully and getting build [here](https://github.com/MacPython/cython-wheels/releases/tag/0.29.23). However, these aarch64 wheels are not available to download from [pypi.org](https://pypi.org/project/Cython/#files). Not sure if aarch64 wheels are getting filtered out. 
Can these wheels be published?

Thanks!
Tanveen

**Comment by tbbharaj** [comment]
Wanted to followup if we can get some inputs regarding getting the aarch64 wheels published to [pypi.org](https://pypi.org/project/Cython/#files).

Thanks!

**Comment by scoder** [comment]
I've uploaded them. Thanks for insisting.

**Comment by tbbharaj** [comment]
Thank you!
